### ISSUE TITLE
Should processes be shown on Android 7 when root access is available?

### ISSUE THREAD

**Issue by reox** [AntonioRedondo/AnotherMonitor#5] opened 2017-06-14 09:16 UTC
I'm not sure if I understood the documentation correct, but should the process list work on android 7.1.2 if root access is available for apps?
I installed AnotherMonitor on my Nexus 5 using LineageOS 14.1 (Android 7.1.2) and activated root but I can not see the list of processes.
I confirmed that root access is working by `su` on a terminal and `ls /proc` works fine.

**Comment by AntonioRedondo** [comment] 2017-08-07 16:52
Hi Reox,

Sorry for the late reply.

AnotherMonitor makes use of the [AndroidProcesses](https://github.com/jaredrummler/AndroidProcesses) library to retrieve system processes. According to its documentation [it's possible](https://github.com/jaredrummler/AndroidProcesses#android-nougat) to get the processes list if you have root access on the device. However I've been unable to check this by my own means.

**Comment by AntonioRedondo** [comment] 2017-08-09 03:46
I've further dug into this. I've tested AnotherMonitor on an rooted Android 7.0 device on the Android emulator and I can confirm it won't show running processes. This is due to the underlying library AndroidProcesses not supporting root access to the `proc` file system.

However the author is aware of this shortcoming and it could implement the feature [soon](https://github.com/jaredrummler/AndroidProcesses/issues/52).

**Comment by AntonioRedondo** [comment] 2017-10-21 09:19
The author of AndroidProcesses has deprecated the library. That means the library won't be updated to support Android 7.0 ever. I'm closing this issue.

**Closed as completed by AntonioRedondo** 2017-10-21 09:19 UTC
Labels: question
